SELECT *
FROM SALES_CONTRACT
WHERE VIN IN (
  SELECT VIN
  FROM INVENTORY
  JOIN DEALERSHIPS ON INVENTORY.dealership_id = DEALERSHIPS.dealership_id
  WHERE DEALERSHIPS.name = 'DOLLS DEALERSHIP'
)
AND date_of_sale BETWEEN 20230101 AND 20251231;