SELECT
DEALERSHIPS.name AS dealership_name
FROM 
VEHICLES
JOIN INVENTORY ON VEHICLES.VIN = INVENTORY.VIN
JOIN DEALERSHIPS ON INVENTORY.dealership_id = DEALERSHIPS.dealership_id
WHERE VEHICLES.make = 'Lexus';
